### Author --- Prem kumar bharti

## Numpy tutorials

* its a general- purpose array processing package
* It is a scientific computing library for python
* Support large no. of data in the form of multi-dimentional array and matrix
* Use for mathematical calculation like linear algebra , fourier transform etc.

An array is a data structure that stores some value of same data type . In python, this is the main difference between lists and arrays. while python list can contain values corresponding to different data types , arrays in python can only contain values corresponding to same data type

In [1]:
import numpy as np

In [2]:
a = list(range(1,11))

In [3]:
abc = np.array(a)

In [4]:
abc

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
type(abc)

numpy.ndarray

In [6]:
n = np.array(range(2 , 11 , 2)) ## Start : end : step

In [7]:
n

array([ 2,  4,  6,  8, 10])

In [8]:
a = np.array([5 , 6 , 7 , "prem"])
a

array(['5', '6', '7', 'prem'], dtype='<U11')

In [9]:
arr_1 = np.array([1,2,3,4,5,6])
arr_1

array([1, 2, 3, 4, 5, 6])

In [10]:
type(arr_1)

numpy.ndarray

In [11]:
print(arr_1.ndim)

1


In [12]:
arr2 = np.array([[1,2,3] , [5 , 6 , 7], [7 , 8 , 9]] , dtype = "str")
arr2

array([['1', '2', '3'],
       ['5', '6', '7'],
       ['7', '8', '9']], dtype='<U1')

In [13]:
print(arr2.size)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)

9
2
(3, 3)
<U1


In [14]:
once = np.ones(5, dtype = int)
once

array([1, 1, 1, 1, 1])

In [15]:
type(once[3])

numpy.int32

In [16]:
ones = np.ones((4,7) , dtype = float)
print(ones)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [17]:
zeros = np.zeros((2,4) ,dtype = int)
print(zeros)
print(zeros.ndim)

[[0 0 0 0]
 [0 0 0 0]]
2


## Arange()

In [18]:
#  np.arange(start , end , steps)
b = np.arange(1,5)
print(b)
print(type(b))
print(b.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [19]:
n = np.arange(1,13,2)
print(n)

[ 1  3  5  7  9 11]


In [20]:
arr_1d = np.arange(1,13)
print(arr_1d)
arr_1d.ndim

[ 1  2  3  4  5  6  7  8  9 10 11 12]


1

## linspace()

In [21]:
np.linspace(1 , 5 , 8)# it will create equal space between numbers

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

## Reshape()

In [22]:
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
arr_2 = arr_1d.reshape(4 , 3) 
print(arr_2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
arr_3 = arr_1d.reshape(2,2,3)
print(arr_3)
print(arr_3.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


## flatten()

In [25]:
arr_2.flatten() # it will create multi-dimentional array into 1 D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
arr_3d = np.arange(1 , 13).reshape(2,2,3)
arr_3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## transpose()

In [28]:
arr_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
arr_2 = arr_2.transpose()
# arr_2 = arr_2.T

In [30]:
arr_2

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [31]:
arr_2.shape

(3, 4)

In [32]:
arr1 = np.arange(1,13).reshape(3,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
arr1 + arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [35]:
arr1 / arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
arr1 * arr2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [37]:
np.multiply(arr1 , arr2)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [38]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
arr1 @ arr2.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [40]:
arr1.dot(arr2.T)

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [41]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
max(arr1.flatten())

12

In [43]:
arr1.max(axis = 0) # max of columns

array([ 9, 10, 11, 12])

In [44]:
arr1.max(axis = 1) # max of rows

array([ 4,  8, 12])

In [45]:
np.sum(arr1)

78

In [46]:
np.sum(arr1 , axis = 1)

array([10, 26, 42])

In [47]:
np.mean(arr1)

6.5

In [48]:
np.cbrt(arr1)

array([[1.        , 1.25992105, 1.44224957, 1.58740105],
       [1.70997595, 1.81712059, 1.91293118, 2.        ],
       [2.08008382, 2.15443469, 2.22398009, 2.28942849]])

In [49]:
arr1**3

array([[   1,    8,   27,   64],
       [ 125,  216,  343,  512],
       [ 729, 1000, 1331, 1728]], dtype=int32)

In [50]:
np.std(arr1)

3.452052529534663

In [51]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [52]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

In [53]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804, 0.90308999],
       [0.95424251, 1.        , 1.04139269, 1.07918125]])

In [54]:
mx = np.arange(1,101).reshape(10,10)
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [55]:
mx[4,3] # rows * column

44

In [56]:
mx[4,3].ndim

0

In [57]:
mx[4:7 , 6 :9]

array([[47, 48, 49],
       [57, 58, 59],
       [67, 68, 69]])